const Ziggy = {"url":"http:\/\/local.bulma-playz.test","port":null,"defaults":{},"routes":{"livewire.upload-file":{"uri":"livewire\/upload-file","methods":["POST"]},"livewire.preview-file":{"uri":"livewire\/preview-file\/{filename}","methods":["GET","HEAD"]},"games.index":{"uri":"games","methods":["GET","HEAD"]},"reset.filter":{"uri":"reset-filter","methods":["GET","HEAD"]},"games.show":{"uri":"games\/{slug}","methods":["GET","HEAD"]},"gamers.register":{"uri":"gamers-register","methods":["POST"]},"users.index":{"uri":"backend\/users","methods":["GET","HEAD"]},"users.create":{"uri":"backend\/users\/create","methods":["GET","HEAD"]},"users.store":{"uri":"backend\/users","methods":["POST"]},"users.show":{"uri":"backend\/users\/{user}","methods":["GET","HEAD"]},"users.edit":{"uri":"backend\/users\/{user}\/edit","methods":["GET","HEAD"]},"users.update":{"uri":"backend\/users\/{user}","methods":["PUT","PATCH"]},"users.destroy":{"uri":"backend\/users\/{user}","methods":["DELETE"]},"comments.index":{"uri":"backend\/comments","methods":["GET","HEAD"]},"comments.create":{"uri":"backend\/comments\/create","methods":["GET","HEAD"],"bindings":{"comment":"id"}},"comments.store":{"uri":"backend\/comments","methods":["POST"]},"comments.show":{"uri":"backend\/comments\/{comment}","methods":["GET","HEAD"]},"comments.edit":{"uri":"backend\/comments\/{comment}\/edit","methods":["GET","HEAD"],"bindings":{"comment":"id"}},"comments.update":{"uri":"backend\/comments\/{comment}","methods":["PUT","PATCH"],"bindings":{"comment":"id"}},"comments.destroy":{"uri":"backend\/comments\/{comment}","methods":["DELETE"]},"backend.moderation":{"uri":"backend\/moderation","methods":["POST"]},"login":{"uri":"login","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]},"register":{"uri":"register","methods":["GET","HEAD"]},"password.request":{"uri":"password\/reset","methods":["GET","HEAD"]},"password.email":{"uri":"password\/email","methods":["POST"]},"password.reset":{"uri":"password\/reset\/{token}","methods":["GET","HEAD"]},"password.update":{"uri":"password\/reset","methods":["POST"]},"password.confirm":{"uri":"password\/confirm","methods":["GET","HEAD"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
